# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cb99db66510d9f3ec2cc2f336c49c36f337c1af5e13aa9f170e0e5a5c49cb3d1fb07c629793460b759337e21639b800669eb2fa2495a956a441edc77e6bf944

test:
  secret_key_base: 568f1d5c14d2003c6ec74461e554ece2f83726a1a03002a6071f037d86a190d4772c7b9d6981dda16d66da2c7d7c09708ce5f118a1b74194acf662c15bddb5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
